version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/greet-user
hooks:
  BeforeInstall:
    - location: scripts/install-dependencies.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: scripts/get-version.sh
      timeout: 300
      runas: root
  ApplicationStop:
    - location: scripts/stop-greet-user.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/deploy-greet-user.sh
      timeout: 300
      runas: root
      environment:
        variables:
          VERSION: #{VERSION}

