version: 0.2
env:
  parameter-store:
    DOCKER_USERNAME: /python-flask/docker/username
    DOCKER_PASSWORD: /python-flask/docker/password
phases:
  install:
    on-failure: ABORT
    runtime-versions:
      python: 3.11
    commands:
      - echo "Installing dependencies...."
      - yum install -y git
  build:
    on-failure: ABORT
    commands:
      - echo "Login to docker registry and create new build"
      - docker login docker.io -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
      - echo "Login completed"
      - echo "Build image..."
      - echo "$CODEBUILD_WEBHOOK_BASE_REF ++++ $CODEBUILD_WEBHOOK_HEAD_REF ++++ $CODEBUILD_WEBHOOK_TRIGGER +++ $CODEBUILD_SOURCE_VERSION"
      - cd $CODEBUILD_SRC_DIR
      - VERSION=$(git branch --contains HEAD | grep -v 'detached' | cut -c 3- | cut -d '-' -f1)
      - docker build -t $DOCKER_USERNAME/greet-user:$VERSION.$CODEBUILD_BUILD_NUMBER .
      - echo "Build completed"
      - echo "Push image......"
      - docker push $DOCKER_USERNAME/greet-user:$VERSION.$CODEBUILD_BUILD_NUMBER
      - echo "Push completed..."
      - VERSION=$VERSION.$CODEBUILD_BUILD_NUMBER
      - export VERSION
      - echo $VERSION > version.txt
artifacts:
  files:
    - version.txt
  base-directory: $CODEBUILD_SRC_DIR

