version: 0.2
run-as: root
env:
  parameter-store:
    DOCKER_USERNAME: /python-flask/docker/username
    DOCKER_PASSWORD: /python-flask/docker/password
phases:
  install:
    on-failure: ABORT
    runtime-versions:
      python: 3.11
    commands:
      - echo "Installing dependencies..."
  build:
    on-failure: ABORT
    commands:
      - echo "Login to docker registry"
      - docker login docker.io -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
      - echo "Login completed"
      - echo "Build image..."
      - docker build -t $DOCKER_USERNAME/greet-user:latest .
      - echo "Build completed"
      - echo "Push image..."
      - docker push $DOCKER_USERNAME/greet-user:$CODEBUILD_BUILD_NUMBER
      - echo "Push completed"